# Generated by Django 3.2.4 on 2021-06-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coke', models.CharField(max_length=5)),
                ('pepsi', models.CharField(max_length=5)),
                ('soda', models.CharField(max_length=5)),
                ('penny_1', models.CharField(max_length=5)),
                ('nickel_5', models.CharField(max_length=5)),
                ('dime_10', models.CharField(max_length=5)),
                ('quarter_25', models.CharField(max_length=5)),
            ],
        ),
    ]
