# Generated by Django 3.2.4 on 2021-06-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penny_1', models.IntegerField(blank=True, null=True)),
                ('nickel_5', models.IntegerField(blank=True, null=True)),
                ('dime_10', models.IntegerField(blank=True, null=True)),
                ('quarter_25', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
