# Generated by Django 3.2.4 on 2021-06-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0004_auto_20210603_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='Cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coins',
            name='Coke',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coins',
            name='Pepsi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coins',
            name='Soda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coins',
            name='dime_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coins',
            name='nickel_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coins',
            name='penny_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coins',
            name='quarter_25',
            field=models.IntegerField(default=0),
        ),
    ]
